“Lesson 3: Add news model, migration, factory and seeder
Corey1337/fefu_backend_2_3 pull request #4
Opened 2021-10-28 11:05 UTC by Corey1337

slug conf

Lesson 3: Add news model, migration, factory and seeder

2021-10-28 16:21 UTC, chrn-feip requested changes

2021-10-28 16:21 UTC, chrn-feip commented on database/migrations/2021_10_23_163149_create_news_table.php
> +            $table->mediumText('description');
Должно быть опциональным

2021-11-01 01:42 UTC, Corey1337 commented on database/migrations/2021_10_23_163149_create_news_table.php
> +            $table->mediumText('description');
А почему так? В тз только про description сказано, что опционально

2021-11-01 01:47 UTC, Corey1337 commented on database/migrations/2021_10_23_163149_create_news_table.php
> +            $table->mediumText('description');
а я понял, извиняюсь

2021-11-01 15:02 UTC, merged