Lesson 6: Validate and sanitize appeal form input
Corey1337/fefu_backend_2_3 pull request #8
Opened 2021-11-10 15:20 UTC by Corey1337

2021-11-11 15:43 UTC, chrn-feip requested changes

2021-11-11 15:43 UTC, chrn-feip commented on database/migrations/2021_11_10_114038_create_new_appeals_table.php
> +class CreateNewAppealsTable extends Migration
ЗАПРЕЩЕНО модифицировать файлы старых миграций. Миграция - это инструкция для изменения БД. Если она выполнена уже, то повторно в штатном режиме (без откатов или пересоздания БД) она НИКОГДА не выполнится. Новые нужды -> новая инструкция -> новый файл миграции.

2021-11-11 15:43 UTC, chrn-feip commented on database/migrations/2021_11_10_114038_create_new_appeals_table.php
> +            $table->string('surname', 40);
Ещё и в down надо писать код. up - применение изменений (в данном случае подразумевали вы добавление столбцов), down  - откат изменений, если понадобится.

2021-11-12 06:39 UTC, Corey1337 commented on database/migrations/2021_11_10_114038_create_new_appeals_table.php
> +class CreateNewAppealsTable extends Migration
Гитхаб это не очень хорошо отображает, но если посмотрите на коммит, то это новый файл с новой миграцией. Я сделал migrate:rollback(вроде такая команда), после удалил файл со старой миграцией, создал новый, переписал его, после сделал migrate. В пгАдминире у меня всё отображает корректно, записывает в таблицу всё тоже нормально

2021-11-12 06:41 UTC, Corey1337 commented on database/migrations/2021_11_10_114038_create_new_appeals_table.php
> +class CreateNewAppealsTable extends Migration
Просто по какой-то причине тут это отображается, как переименованный файл с изменениями, а не удаление старого, и создание нового

2021-11-12 06:50 UTC, chrn-feip commented on database/migrations/2021_11_10_114038_create_new_appeals_table.php
> +class CreateNewAppealsTable extends Migration
![image](https://user-images.githubusercontent.com/40585429/141422924-7fca163f-9b8d-446d-bee9-0a49798c3a37.png)
Это отображается как переименование, потому что удаление и создание нового файла произошли в одном коммите, а контент новой дублирует старую.
Вам не нужно ничего делать со старой миграцией. Нужно создать новую. И не новую таблицу в ней делать, а модифицировать уже созданную (создавалась она как раз в старой миграции).

2021-11-12 06:51 UTC, chrn-feip requested changes

2021-11-12 06:51 UTC, chrn-feip commented on database/migrations/2021_11_10_114038_create_new_appeals_table.php
> +class CreateNewAppealsTable extends Migration
И под модификацией я имею в виду не только редактирование кода, но и любые другие изменения - переименование, удаление и т.п.

2021-11-12 09:17 UTC, chrn-feip requested changes

2021-11-12 09:17 UTC, chrn-feip commented on database/migrations/2021_11_12_073652_create_appeal_table.php
> +class CreateAppealTable extends Migration
Сделайте так, чтобы в коммите не было вообще старой миграции. Переименовывать файл нельзя. Менять название класса тоже ни к чему.

2021-11-12 11:19 UTC, merged